DROP TABLE IF EXISTS addresses CASCADE;

CREATE TABLE addresses(
  id SERIAL PRIMARY KEY NOT NULL,
  title VARCHAR(255) NOT NULL,
  lat VARCHAR(255) NOT NULL,
  lng VARCHAR(255) NOT NULL,
  user_id INTEGER REFERENCES users(id)
);